### ISSUE TITLE
Can't install on macOS

### ISSUE THREAD

**Issue by m3nu** [cheat/cheat#431]
Running into a similar issue as #420 on macOS. Installing without `CHEAT_PATH` fails:

`error: could not create '/usr/share/cheat': Operation not permitted` (this dir is protected since High Sierra and can't be modified)

With `CHEAT_PATH` set, it fails a bit later:

`error: could not create '/etc/cheat': Permission denied` (can be modified with SUDO-permissons)

When looking at `setup.py`, both folders are mentioned there, but only the first can be overridden. I don't know of any other Python package that writes to those paths. How about sticking to user-folders and letting the platform itself (like Homebrew or a Linux package maintainer) choose if and where to store those "shared" cheat files?

**Comment by chrisallenlane** [comment]
@m3nu 

Thanks for bringing this to my attention. I am unable to test on any Mac platform personally.

I just opened #432 to (hopefully) resolve this problem. When you have a moment, please attempt to install `cheat` again from the `installation-issues` branch, which includes the proposed changes.

If that resolves your problem, I'll merge in the PR and release an update after informing the necessary stakeholders.

**Comment by m3nu** [comment]
Works great on macOS. Added some comments to the PR.

One thing to consider is that the change is not backwards-compatible. Users need to move their cheats out of `~/.cheat`, which is OK, but worth mentioning. Also reminds me of the [recent discussion about dotfiles on HN](https://news.ycombinator.com/item?id=19063727).

**Comment by m3nu** [comment]
Suggestion for an updated README regarding file locations:

"""
Before version XX, cheat files were kept in `/etc/cheat` for system-wide config files and in `~/.cheat` for user-specific cheat files.

Starting from version YY, a system-specific path is used. Here some examples for popular systems:

- macOS: `~/Library/Application Support/cheat`
- Linux: `~/.config/cheat` ??
- Windows: `???`

If you have existing cheat files in the old locations, you can either move them to the new location or set the env variable `CHEAT_PATH`.
"""

For even more clarity, the `cheat -l` command could show the current paths at the top.

**Comment by chrisallenlane** [comment]
@m3nu 

Thanks very much for the detailed feedback. This is very helpful.

This morning I pushed another commit that should resolve the issues related to `appdirs`. (I'm simply including it within the project now, rather than attempting to install it via `pip`.)

Tomorrow I'll attempt to resolve the issues regarding `~/.cheat`. I agree that we don't want to force users to move their cheatsheets. (I also agree that there is value in conforming to the XDG standards regarding where we choose to store data.) I will also update the `README` verbiage.

Thanks for the help. I will ping you on here when this branch is ready to be re-tested.

**Comment by chrisallenlane** [comment]
@m3nu 

(CC'ing @Almenon, @bernermic, @shanahanjrs, @TomasKorbar)

I pushed more changes to #432. When you have a moment, please re-test your installation from this branch. I *think* `cheat` should now install successfully.

Something to note and discuss here:

Ultimately, I decided to keep user-created cheatsheets in `~/.cheat` by default, contrary to the XDG guidelines.

I did this because, per #351, we're trying to obviate the need to use `sudo` when installing cheat. That being the case, I decided to install "system-wide" cheatsheets to the `user_data_dir` reported by `appdirs`.

If I installed user-defined cheetsheets to the same directory, it is probable that users would have their own cheatsheets overwritten every time `cheat` was updated, which we obviously want to avoid. By storing user-defined cheatsheets in `~/.cheat`, we solve that problem, even though we do pollute the user's home directory somewhat. (FWIW, I personally keep my own cheatsheets in `~` intentionally. It makes it easy to keep them backed-up and tracked along with the rest of my dotfiles.)

There is another possible approach, of course:

If we decide that we don't mind mandating the use of `sudo` during the installation process, we could store system-wide cheatsheets to `site_data_dir`, and personal cheatsheets to `user_data_dir`. We'd be fully XDG-compliant that way, though we'd be arguably be violating Python's best-practices.

That approach is probably more standard. It's arguably less safe and secure. I don't think `cheat` is a particularly high-risk application, though, from a security perspective. Also, upstream maintainers will likely require the use of `sudo` when installing from third-party repositories regardless.

I'm personally torn about this. If you have input, please share it here. Otherwise, I'll think about this for a bit, and will make a judgement call.

@TomasKorbar, @bernermic: FYI, I'll ask you two to re-test your builds before I merge this, once again to ensure that I don't break your packages. Hopefully, now that we're resolving these installation-related problems soon, I won't have to bother either of you much longer after that :smile:

**Comment by Almenon** [comment]
I'm in favor of a approach that doesn't require sudo, although I don't have much experience with Linux so I can't say for sure whether that is the approach you should take.

**Comment by m3nu** [comment]
> I'm in favor of a approach that doesn't require sudo, although I don't have much experience with Linux so I can't say for sure whether that is the approach you should take.

To weigh in on this: It's bad practice to install packages into the system Python using `sudo`. This is true for both – Linux and macOS. General practice is to either use `pip install --user XXX`, which will still use the system Python, but install the package to the current user's home folder only. Another option is to install a custom Python distribution belonging to the current user. Anaconda and Pyenv are both doing that. Then you install any package into that custom Python without messing up the system Python.

`cheat` fits nicely with the latter two install options and should work with both without needing `sudo`. If a (Linux) distribution decides to package `cheat`, they will integrate it into the system Python themselves and maybe put files into `/etc/cheat` if they seem fit. `cheat` itself can not and should not make this decision. It should just behave like a normal Python package.

If someone insists on installing `cheat` with `sudo` they can still do that, but it will be the minority. One use case would be to make `cheat` available for all users on the system when there is no distribution package available. (bonus question: Where to put pre-packaged cheats in that case? See below for an option.)

Keeping user cheat files in `~/.cheat` and pre-packaged cheats in `user_data_dir`  is totally fine and doesn't break the setup of existing users. I also like `~/.cheat` for easy access when editing files. It's also a good idea to not touch `~/.cheat`. I had lots of files added there when testing the last PR and removed them again.

One more thing to consider: Is it necessary to even copy pre-packaged cheat files to `user_data_dir` or could they just live in the package with `~/.cheat` having higher priority for equal names? If I delete `user_data_dir`, should it get re-created after each update? If pre-packaged files would stay inside the package, it would also work nicely when installing it for multiple users with `sudo pip`.

So my answers to the above questions in short:

- "keep user-created cheatsheets in `~/.cheat`" - Yes, great.
- "install "system-wide" cheatsheets to the `user_data_dir`" – OK, but they could also stay in the Python package, which would make them available system-wide without much hassle.
- "we don't mind mandating the use of `sudo`" – I would avoid `sudo` together with `pip` at all cost. Linux maintainers requiring `sudo apt/yum/etc` is different.

**Comment by TomasKorbar** [comment]
Hi guys,
First i want to apologize for delay.
Second, @chrisallenlane these changes break rpm package of cheat. Tomorrow i will provide fork with changes which, with your agreement, should identify fedora or redhat based distributions and search for files in directories complying with filesystem hiearchy standard which we are using.

**Comment by TomasKorbar** [comment]
Update @chrisallenlane 
I managed to get around of these changes in rpm package, so this approach is ok from my point of view.
I just want to point out that i kept getting ModuleNotFoundError after installation untill i fixed appdirs import call like this https://github.com/TomasKorbar/cheat/commit/fdc414ede385906622f60455904c6b32d0dc0e15

**Comment by ryanjbonnell** [comment]
I commented on being able to install Cheat on macOS in #432 from the `installation-issues` branch, but even so it still relied on having pip installed and given sudo access.

Understandably for many, the widespread use and ease of installing via Homebrew is appealing, so it would be desirable to have the latest version of Cheat readily available in Homebrew.

Until then, you could follow the [manual installation instructions in the Pull Request](https://github.com/cheat/cheat/pull/432#issuecomment-519769394) and helping test the changes at the same time.

**Comment by chrisallenlane** [comment]
Hi, guys

I have just released `cheat` v3, which was re-written entirely in Golang. As such, the Python installer issues have been made moot: the "installation" procedure is now "just download the executable".

That said, this should be resolved. Please upgrade and let me know if you encounter any errors.

Thanks!

**Comment by Almenon** [comment]
I'm curious, why the switch? How do you find golang compared to python?

**Comment by FlorianKempenich** [comment]
@Almenon 
He explained here: https://github.com/cheat/cheat/issues/470#issue-488755136

**Comment by chrisallenlane** [comment]
Thanks for the link, @FlorianKempenich. That is the definitive source on the question.

@Almenon, in general, I strongly prefer Go. One lesson I've learned the hard way (both here and with other projects) is not to write desktop software in a scripting language. Entirely too often the project seems to "burn down" the moment you turn away, as dependencies change beneath you. (I've encountered this problem with python, node, and ruby. Lockfiles only get you so far.)

This isn't a huge problem when writing server applications - such applications tend to be run inside single-purpose docker containers or whatever, so it's reasonable to expect that server applications will be hosted from an environment that's tailored to their needs. This is not true of desktop software, however.

**Comment by Almenon** [comment]
Thanks for the explanation! Switching to go makes a lot of sense given that you have experience in go. 

> Entirely too often the project seems to "burn down" the moment you turn away, as dependencies change beneath you. (I've encountered this problem with python, node, and ruby. Lockfiles only get you so far.)

I'm curious what you mean by this. Lockfiles in the version so the dependency can't change  - that doesn't fix the problem?

**Comment by chrisallenlane** [comment]
> Lockfiles in the version so the dependency can't change - that doesn't fix the problem?

Yeah, it's a sneaky problem, because you'd think lockfiles would solve this. But here's a real-life example:

https://github.com/chrisallenlane/node-did

I wrote that a few years ago, probably on node 6 or something. It doesn't work anymore on my local machine, though, because I'm running node 12. While the lockfile does, in fact, guarantee that this app will run on node 6, it depends on modules that are incompatible with node 12.

So, now I'm forced to make a decision - which software do I want to use? This thing, or the stuff that runs in node 12? I'm not going to run node 6 for the rest of my life, so I guess `node-did` is just dead until I likewise re-write it in Go or Rust or something :/

This problem really snuck up on me. Lockfiles seemed like the answer, but they really aren't. The only real answer, I've come to believe, are compiled binaries with no system-level dependencies.
